name: CI

on:
  pull_request:

permissions:
  contents: write
jobs:
  build:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    permissions:
      contents: write
      statuses: write

    steps:
      - name: Run tests
        run: |
          export PATH="$PATH:/opt/qemu/bin"
          export PATH="$PATH:/local/mnt/workspace/riscv32-unknown-linux-gnu/bin"

          export ELD_RISCV32_C_COMPILER=riscv32-unknown-linux-gnu-cc
          export ELD_RISCV32_CXX_COMPILER=riscv32-unknown-linux-gnu-c++
          export ELD_RISCV32_SYSROOT=/local/mnt/workspace/riscv32-unknown-linux-gnu/riscv32-unknown-linux-gnu/sysroot

          which qemu-riscv32
          qemu-riscv32 --version

          which riscv32-unknown-linux-gnu-cc
          file `which riscv32-unknown-linux-gnu-cc`
          riscv32-unknown-linux-gnu-cc --version

          which riscv32-unknown-linux-gnu-c++
          file `which riscv32-unknown-linux-gnu-c++`
          riscv32-unknown-linux-gnu-c++ --version

          grep -Iir GPL /local/mnt/workspace/riscv32-unknown-linux-gnu/riscv32-unknown-linux-gnu/sysroot

          cat `which riscv32-unknown-linux-gnu-cc`
          cat `which riscv32-unknown-linux-gnu-c++`

      - name: Clean up
        if: always()
        run: |
          rm -rf "pr-${{ env.PR_NUMBER }}"
